config/routes.rb
Rails.application.routes.draw do
  resources :task_categories
  resources :categories
  root 'tasks#index'

  resources :tasks do
    get :add_category, on: :collection
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :task_categories
	has_many :tasks, through: :task_categories 
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :task_categories
	has_many :categories, through: :task_categories

	accepts_nested_attributes_for :task_categories, allow_destroy: true,:reject_if => lambda {|a| a[:category_id].blank?}
end

app/models/task_category.rb
class TaskCategory < ActiveRecord::Base
	belongs_to :task
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/task_categories_controller.rb
class TaskCategoriesController < ApplicationController
  before_action :set_task_category, only: [:show, :edit, :update, :destroy]

  # GET /task_categories
  # GET /task_categories.json
  def index
    @task_categories = TaskCategory.all
  end

  # GET /task_categories/1
  # GET /task_categories/1.json
  def show
  end

  # GET /task_categories/new
  def new
    @task_category = TaskCategory.new
  end

  # GET /task_categories/1/edit
  def edit
  end

  # POST /task_categories
  # POST /task_categories.json
  def create
    @task_category = TaskCategory.new(task_category_params)

    respond_to do |format|
      if @task_category.save
        format.html { redirect_to @task_category, notice: 'Task category was successfully created.' }
        format.json { render :show, status: :created, location: @task_category }
      else
        format.html { render :new }
        format.json { render json: @task_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_categories/1
  # PATCH/PUT /task_categories/1.json
  def update
    respond_to do |format|
      if @task_category.update(task_category_params)
        format.html { redirect_to @task_category, notice: 'Task category was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_category }
      else
        format.html { render :edit }
        format.json { render json: @task_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_categories/1
  # DELETE /task_categories/1.json
  def destroy
    @task_category.destroy
    respond_to do |format|
      format.html { redirect_to task_categories_url, notice: 'Task category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_category
      @task_category = TaskCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_category_params
      params.require(:task_category).permit(:task_id, :category_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :all_tasks, only: [:index, :create]


  # GET /tasks
  # GET /tasks.json
  def index
    @task = Task.new
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  #def add_category
  #  @task.task_categories.push(TaskCategory.new)
  #  respond_to do |format|
  #    format.html
  #    format.js
  #  end
  #end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.save
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
   #@task.update(:task_categories_attributes => :id => {:category_id => params[:category_id]})
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def all_tasks
      @tasks = Task.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :due, :strict, :duration, :scheduled, :complete, :task_categories_attributes => [:id, :category_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_categories(name, f, association)
		new_object = TaskCategory.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render("nested_fields", f:builder)
		end
		link_to(name, '#', class: "add_categories", data: {id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/form_helper.rb
module FormHelper
	def setup_task(task)
		if task.task_categories.length ==0
			task.task_categories.push TaskCategory.new
		end
		task
	end
end

app/helpers/task_categories_helper.rb
module TaskCategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
	def add_category
	end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskmanager</title>

  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/task_categories/_form.html.erb
<%= form_for(@task_category) do |f| %>
  <% if @task_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_category.errors.count, "error") %> prohibited this task_category from being saved:</h2>

      <ul>
      <% @task_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.number_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_categories/edit.html.erb
<h1>Editing Task Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_category %> |
<%= link_to 'Back', task_categories_path %>

app/views/task_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Task Categories</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_categories.each do |task_category| %>
      <tr>
        <td><%= task_category.task_id %></td>
        <td><%= task_category.category_id %></td>
        <td><%= link_to 'Show', task_category %></td>
        <td><%= link_to 'Edit', edit_task_category_path(task_category) %></td>
        <td><%= link_to 'Destroy', task_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task category', new_task_category_path %>

app/views/task_categories/new.html.erb
<h1>New Task Category</h1>

<%= render 'form' %>

<%= link_to 'Back', task_categories_path %>

app/views/task_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @task_category.task_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @task_category.category_id %>
</p>

<%= link_to 'Edit', edit_task_category_path(@task_category) %> |
<%= link_to 'Back', task_categories_path %>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.datetime_select :due %>
  </div>
  <div class="field">
    <%= f.label :strict %><br>
    <%= f.number_field :strict %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.datetime_select :duration %>
  </div>
  <div class="field">
    <%= f.label :scheduled %><br>
    <%= f.datetime_select :scheduled %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.number_field :complete %>
  </div>
  
  <%= f.fields_for :task_categories do |builder| %>
    <%= render "nested_fields", f: builder %>
  <% end %>
  <%= link_to_add_categories "Add Category", f, :task_categories %> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_nested_fields.html.erb
<div>
	<%= f.collection_select(:category_id, Category.all, :id, :name, include_blank: true) %>
	<%= f.hidden_field :_destroy %>
	<button type="button" class ="remove_field" style="display:inline">X</button>
</div>

app/views/tasks/_task.html.erb
<tr>
  <td><%= task.name %></td>
  <td><%= task.due.strftime("%-m/%-d/%y") %></td>
  <td><%= task.scheduled.strftime("%-m/%-d/%y") %></td>
  <td>
    <%if task.complete == 1 %>
      <span class="glyphicon glyphicon-ok"></span>
    <%end%>
  </td>

  <td><%= link_to 'Show', task %></td>
  <td><%= link_to 'Edit', edit_task_path(task) %></td>
  <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/tasks/add_category.js.erb
$("form").html("<%=j render "tasks/form", locals: {@task} %>")

app/views/tasks/create.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<div class="row">
  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Due</th>
          <th>Scheduled</th>
          <th>Complete</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody id="tasks">
        <%= render @tasks %>
      </tbody>
    </table>
  </div>
  <div class ="col-md-6">
    <%= link_to 'New Task', new_task_path, remote: true %>
    <div id="task-form" style="display:none;"></div>
  </div>
</div>

<br>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

$(".remove_field").click(function(){
	$(this).parent().hide();
	$(this).prev('input[type=hidden]').val('1');
});

$(".add_categories").click(function(){
	time = new Date().getTime()
	regexp = new RegExp($(this).data('id'), 'g')
	$(this).before($(this).data('fields').replace(regexp, time))
	event.preventDefault()
});

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Due:</strong>
  <%= @task.due %>
</p>

<p>
  <strong>Strict:</strong>
  <%= @task.strict %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @task.duration %>
</p>

<p>
  <strong>Scheduled:</strong>
  <%= @task.scheduled %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @task.complete %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>